### ISSUE TITLE
Folder Permissions Bug (Installer)

### ISSUE THREAD

**Issue by DavidCarbon** [1DavidCarbon/Soapbox_Launcher_Installer#6]
- **Launcher Version:** ALL
- **Operating system:** Windows
- **Antivirus/Firewall (if any):** Both

**Description of issue:**
Installer changes permissions causing game launcher updater to fail.
![Permissions](https://cdn.discordapp.com/attachments/484873294634418206/513928582381436929/unknown.png)
![Its set to](https://cdn.discordapp.com/attachments/484873294634418206/513928993137885184/unknown.png)
![Should be](https://cdn.discordapp.com/attachments/484873294634418206/513929115401846796/unknown.png)

**Comment by 1DavidCarbon** [comment]
Operating system: Windows 7 (Maybe Windows 8 as well)

**Comment by 1DavidCarbon** [comment]
After debugging to issue for an hour I have come to a conclusion. Folder permissions was not set due to Windows 10 doesn't need this, but Windows 7 does... Whoops
![Installer version 1.9.58 and older](https://cdn.discordapp.com/attachments/484873294634418206/513974741783150592/File_Explorer_1.PNG)
Screenshot shows what files were "locked" before the new fix and an after screenshot fix.
![Installer version 1.9.60](https://cdn.discordapp.com/attachments/484873294634418206/513974904681529344/File_Explorer_2.PNG)
Thanks Nevada789#9254 on this issue.
